flowchart TB
  Internet["Citizen Internet Traffic"] --> WAF["AWS WAF + Shield"]
  WAF --> NLB["Internet NLB (DMZ)"]
  NLB --> Ingress["NGINX Ingress (App LB)"]
  Ingress --> FE["React SPA Rollout"]
  Ingress --> API["FastAPI Rollout"]
  API --> Redis["Redis HA"]
  API --> PG["PostgreSQL Multi-AZ"]
  API --> S3["S3 Object Storage"]

  OnPrem["On-Prem Departments"] --> VPN["Site-to-Site VPN"]
  VPN --> VPC["AWS VPC"]

  PG --> PGDR["Postgres DR Replica"]
  Redis --> RedisDR["Redis Global Replica"]
  S3 --> S3DR["S3 CRR Bucket"]
